apiVersion: apps/v1
kind: Deployment
metadata:
  name: downloader-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: downloader-service
  template:
    metadata:
      labels:
        app: downloader-service
    spec:
      containers:
        - name: downloader-service
          image: downloader-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://config-server:8888"
            - name: STORAGE_SERVICE_URL
              value: "http://storage-service:8081"
---
apiVersion: v1
kind: Service
metadata:
  name: downloader-service
spec:
  selector:
    app: downloader-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  #type: NodePort