server:
  port: 8083
  address: 0.0.0.0
spring:
  application:
    name: fetcher-service
  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true
      retry:
        initial-interval: 1500
        max-interval: 10000
        multiplier: 1.5
        max-attempts: 10
  profiles:
    active: default
  config:
    import: "optional:configserver:"