apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetcher-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fetcher-service
  template:
    metadata:
      labels:
        app: fetcher-service
    spec:
      containers:
        - name: fetcher-service
          image: fetcher-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://config-server:8888"
            - name: STORAGE_SERVICE_URL
              value: "http://storage-service:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: fetcher-service
spec:
  selector:
    app: fetcher-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  #type: NodePort