apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  username: cm9vdA==  # base64 encoded 'root'
  password: YWRtaW4xMjM0  # base64 encoded 'admin1234'
  root-password: YWRtaW4xMjM0  # base64 encoded 'admin1234'