server:
  port: 8080

spring:
  application:
    name: api-service

# Add any other necessary configurations, such as:
# - Service discovery settings
# - Circuit breaker settings
# - Logging configurations
# - etc.

downloader:
  service:
    url: http://downloader-service:8080
fetcher:
  service:
    url: http://fetcher-service:8080