server:
  port: 8080  # Choose an appropriate port

spring:
  application:
    name: api-service
  datasource:
    url: jdbc:mysql://mysql:3306/alpha
    username: root
    password: admin1234

# Add any other necessary configurations, such as:
# - Service discovery settings
# - Circuit breaker settings
# - Logging configurations
# - etc.

downloader:
  service:
    url: http://downloader-service:8082
fetcher:
  service:
    url: http://fetcher-service:8081