server:
  port: 8080
  address: 0.0.0.0

storage:
  api:
    save-all: ${storage.service.url}/storage/saveAll

alpha:
  apiKey: 2NYM2EF6HJZUCXAL
  baseUrl: https://www.alphavantage.co/query?function=

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always