server:
  port: 8080
  address: 0.0.0.0

storage:
  api:
    between: ${storage.service.url}/storage/between

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
