server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/alpha
    username: root
    password: admin1234
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always